import type { DailyReport, SessionReport } from '../types';

export function generateMarkdownFromReport(report: DailyReport, selectedSession?: SessionReport): string {
  const lines: string[] = [];
  
  // 리포트 헤더
  lines.push(`# ${new Date(report.date).toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'long'
  })} 리포트`);
  lines.push('');
  lines.push(`> ${report.summary}`);
  lines.push('');
  lines.push('---');
  lines.push('');
  
  // 세션 정보
  if (selectedSession) {
    // 단일 세션 내보내기
    lines.push(...generateSessionMarkdown(selectedSession));
  } else {
    // 전체 세션 내보내기
    lines.push(`## 세션 목록 (총 ${report.sessions.length}개)`);
    lines.push('');
    
    report.sessions.forEach((session, index) => {
      if (index > 0) {
        lines.push('');
        lines.push('---');
        lines.push('');
      }
      lines.push(...generateSessionMarkdown(session, index + 1));
    });
  }
  
  // 푸터
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated by Claude Report Analyzer on ${new Date().toLocaleString('ko-KR')}*`);
  
  return lines.join('\n');
}

function generateSessionMarkdown(session: SessionReport, sessionNumber?: number): string[] {
  const lines: string[] = [];
  
  // 세션 제목
  const titlePrefix = sessionNumber ? `### ${sessionNumber}. ` : '## ';
  lines.push(`${titlePrefix}${session.title}`);
  lines.push('');
  
  // 세션 요약
  lines.push(`**요약:** ${session.summary}`);
  lines.push('');
  
  // 주요 토픽
  if (session.keyTopics && session.keyTopics.length > 0) {
    lines.push('#### 📌 주요 토픽');
    lines.push('');
    session.keyTopics.forEach(topic => {
      lines.push(`- \`${topic}\``);
    });
    lines.push('');
  }
  
  // AI 분석 결과
  if (session.aiInsights) {
    lines.push('#### 🤖 AI 분석 결과');
    lines.push('');
    
    // 주요 인사이트
    if (session.aiInsights.keyInsights && session.aiInsights.keyInsights.length > 0) {
      lines.push('**주요 인사이트:**');
      lines.push('');
      session.aiInsights.keyInsights.forEach(insight => {
        lines.push(`- ${insight}`);
      });
      lines.push('');
    }
    
    // 기술 상세
    if (session.aiInsights.technicalDetails) {
      if (session.aiInsights.technicalDetails.languages && session.aiInsights.technicalDetails.languages.length > 0) {
        lines.push(`**사용 언어:** ${session.aiInsights.technicalDetails.languages.join(', ')}`);
        lines.push('');
      }
      if (session.aiInsights.technicalDetails.frameworks && session.aiInsights.technicalDetails.frameworks.length > 0) {
        lines.push(`**프레임워크:** ${session.aiInsights.technicalDetails.frameworks.join(', ')}`);
        lines.push('');
      }
    }
    
    // 코드 품질
    if (session.aiInsights.codeQuality) {
      if (session.aiInsights.codeQuality.strengths && session.aiInsights.codeQuality.strengths.length > 0) {
        lines.push('**✅ 강점:**');
        lines.push('');
        session.aiInsights.codeQuality.strengths.forEach(strength => {
          lines.push(`- ${strength}`);
        });
        lines.push('');
      }
      
      if (session.aiInsights.codeQuality.improvements && session.aiInsights.codeQuality.improvements.length > 0) {
        lines.push('**⚠️ 개선사항:**');
        lines.push('');
        session.aiInsights.codeQuality.improvements.forEach(improvement => {
          lines.push(`- ${improvement}`);
        });
        lines.push('');
      }
    }
    
    // 타임라인
    if (session.aiInsights.timeline) {
      lines.push('**📅 작업 타임라인:**');
      lines.push('');
      
      if (session.aiInsights.timeline.mainTasks && session.aiInsights.timeline.mainTasks.length > 0) {
        lines.push('*주요 작업:*');
        session.aiInsights.timeline.mainTasks.forEach(task => {
          lines.push(`- ✓ ${task}`);
        });
        lines.push('');
      }
      
      if (session.aiInsights.timeline.completedGoals && session.aiInsights.timeline.completedGoals.length > 0) {
        lines.push('*완료된 목표:*');
        session.aiInsights.timeline.completedGoals.forEach(goal => {
          lines.push(`- ✓ ${goal}`);
        });
        lines.push('');
      }
      
      if (session.aiInsights.timeline.challenges && session.aiInsights.timeline.challenges.length > 0) {
        lines.push('*해결한 문제:*');
        session.aiInsights.timeline.challenges.forEach(challenge => {
          lines.push(`- 🔧 ${challenge}`);
        });
        lines.push('');
      }
    }
  }
  
  // 상세 내용
  if (session.mdxContent) {
    lines.push('#### 📝 상세 내용');
    lines.push('');
    lines.push(session.mdxContent);
    lines.push('');
  }
  
  return lines;
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}